### ISSUE TITLE
211125 Sprint day4

### ISSUE THREAD

**Issue by seungjaepack** [SSAC-Main-Team-PRJ/PRJ-Epic#7]
Sprint Day 3 Review(AM 10:10 ~ AM 10:40) :

- [x] Review 1 : Main Tasks

# Sprint Day 4 Goal :
- [x]  1. 역세권 : 위도/경도를 이용하여 거리 변수 추가
- [x]  2.  공공데이터 데이터 수집 (학교)

**Comment by seungjaepack** [comment]
## 프로젝트 전체 일정
- 데이터 수집 완료 : 11월 26일(금요일)
- 데이터 전처리 완료 : 11월 30일 (화요일)
- EDA 완료 : 12월 2일 (목요일)
- 모델링 : 12월 3일 (금요일)
- 모델 평가 완료 : 12월 6일(월요일)
- 프로젝트 레포트 최종 작성일 : 12월 7일 (화요일)
- 프로젝트 최종 리뷰 : 12월 8일(수요일) ~ 12월 9일(목요일)
- 프로젝트 발표 : 12월 10일 (금요일)

**Comment by whynotg** [comment]
서울시 아파트별 산책 생활권 정보 ->  단지명, 세대수, 법정동주소, 코스수
apt info ->  주소(시군구), 주소(읍면동), 전체 동수, 주차대수,  세대수, 건설사

각 파일별 필요한 컬럼들은 위와 같고, 병합시에 중복 칼럼은 삭제 해주시면 됩니다. 
주소는 구와 동으로 컬럼이 나누어 지는게 활용도가 좋을것 같아요.
아마 아파트 이름이나 단지명으로 추리시면 될것같습니다. 가능한 작업까지만 부탁드리겠습니다

**Comment by seungjaepack** [comment]
> 서울시 아파트별 산책 생활권 정보 -> 단지명, 세대수, 법정동주소, 코스수 apt info -> 주소(시군구), 주소(읍면동), 전체 동수, 주차대수, 세대수, 건설사
> 
> 각 파일별 필요한 컬럼들은 위와 같고, 병합시에 중복 칼럼은 삭제 해주시면 됩니다. 주소는 구와 동으로 컬럼이 나누어 지는게 활용도가 좋을것 같아요. 아마 아파트 이름이나 단지명으로 추리시면 될것같습니다. 가능한 작업까지만 부탁드리겠습니다

**Comment by seungjaepack** [comment]
아파트 dataset과 산책 생활권 정보 합친 파일 구글 드라이브에 공유했습니다~

**Comment by seungjaepack** [comment]
## 11월 26일 오전 리뷰 할 내용
### 1. 모델 점수 입력 결과 공유하기
- dacon data set으로 예측 값을 submission file에 넣어서 점수 확인해보기
### 2. 코드 동작시 이슈 공유 하기
